name: "Print XY Values"
description: "A simple action to print x and y values"
inputs:
  x:
    description: "First number"
    required: true
  y:
    description: "Second number"
    required: true
runs:
  using: "composite"
  steps:
    - run: echo "x = ${{ inputs.x }}, y = ${{ inputs.y }}"
      shell: bash
