name: gitaction
inputs:
  x:
    default: 0
  y:
    default: 0
runs:
  using: "composite"
  steps:
    - run: echo "Hi, I'm a gitaction!"
      shell: bash
    - run: echo "x = ${{ inputs.x }}, y = ${{ inputs.y }}"
      shell: bash
