name: CI
on: push
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Print x and y values
        uses: ./github/actions/print-xy
        with:
          x: 12
          y: 3
