name: Our Workflow
on: push
jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4
      with: 
        repository: Jesuji/gitaction
          token: ${{ secrets.GITHUB_TOKEN }}

          - name: Run a custom action
        run: echo $((12 + 3))
        shell: bash
